# -*- coding: utf-8 -*-
"""lab-jupyter-logistic-regression-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178sjFD95JZuX9aRgjuORD-36CMr3nTIk

<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Logistic Regression**

Estimated time needed: **30** minutes

In this lab, you will learn about and get hands-on practice with the logistic regression model, a popular and effective classification model. Understanding logistic regression and being able to apply it to classification tasks is essential because logistic regression models form the fundamentals of neural networks.

We will use a real-world dataset that contains detailed nutrition information about food items for people with diabetes. The objective is to classify whether a diabetic patient should choose More Often, Less Often, or In Moderation for a specific food item based on the nutrition information in the dataset.

## Objectives

After completing this lab you will be able to:

*   Preprocess and generate training and testing datasets
*   Train and fine-tune logistic regression models
*   Interpret trained logistic regression models
*   Evaluate trained logistic regression models

***

## Prepare and setup lab environment
"""

# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.3 numpy==1.21.2 ipywidgets==7.4.2 scipy==7.4.2 tqdm==4.62.3 matplotlib==3.5.0 seaborn==0.9.0
# Note: If your environment doesn't support "!mamba install", use "!pip install"

!pip install -U scikit-learn
!pip install pandas
!pip install numpy
!pip install seaborn
!pip install matplotlib

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix,ConfusionMatrixDisplay, precision_recall_fscore_support, precision_score, recall_score
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# also set a random state
rs = 123

"""### Exploratory Data Analysis(EDA) and Feature Engineering
Before we get to the model implementation, it is essential to examine the dataset and carefully select the features that will serve as inputs for the model..

### Load and explore the dataset

First, let's load the dataset as a `Pandas` dataframe and conduct some basic EDA tasks on it.
"""

# Load the dataset
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML241EN-SkillsNetwork/labs/datasets/food_items.csv"
food_df = pd.read_csv(dataset_url)

"""And, let's quickly check its column types.

"""

food_df.head()

food_df.shape

food_df.dtypes.value_counts()

"""Print the first ten food items:

"""

food_df.select_dtypes(include='object').head(2)

food_df.head(5)

"""Get the row entries with col 0 to -1 (16).

"""

feature_cols = list(food_df.iloc[:, :-1].columns)
feature_cols

"""Obtain descriptive statistics:

"""

food_df.iloc[:, :-1].describe()

"""As we can see from the above output, this dataset contains 17 nutrient categories about each food item. These categories include Calories, Total Fat, Protein, Sugar, etc., and are listed as numeric variables. As such, we only need to scale them for training our logistic regression model so that we can compare our feature coefficients directly. This will be done under the feature engineering section.

Next, let's check the target variable in the `class` column to see the label values and their distribution.
"""

# # Get the row entries with the last col 'class'
food_df.iloc[:, -1:].value_counts(normalize=True)*100

food_df.iloc[:, -1:].value_counts().plot.bar(color=['black', 'orange', 'purple'])

"""As we can see from the bar chart above, this dataset has three classes: `In Moderation`, `Less Often`, and `More Often`. The three labels are imbalanced. For diabetic patients, most food items are in the In Moderation and Less Often categories. This makes diabetes diet management very hard, so we could build a machine learning model to help patients choose their food.

We have three labels meaning our logistic regression model will be multinomial with three classes.

A multinomial logistic regression is a generalized logistic regression model which generates a probability distribution over all classes, based on the logits or exponentiated log-odds calculated for each class (usually more than two).

Also note that a multinomial logistic regression model is different from the `one-vs-rest` binary logistic regression. For `one-vs-rest` schema, you need to train an independent classifier for each class. For example, you need a `More Often` classifier to differentiate a food item between `More Often` and `Not More Often` (or, `In Moderation` and `Less Often`).

### Feature Engineering

Now you should have some basic understanding about the food dataset. Next, let's process the raw dataset and construct input data `X` and label/output `y` for logistic regression model training.
"""

X_raw = food_df.iloc[:, :-1]
y_raw = food_df.iloc[:, -1:]

"""Fortunately, all feature columns are numeric so we just need to scale them. Here we use the `MinMaxScaler` provided by `sklearn` for scaling.

"""

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Scaling the raw input features
X = scaler.fit_transform(X_raw)

"""Let's check the scaled feature value range:

"""

print(f"The range of feature inputs are within {X.min()} to {X.max()}")

"""For the target variable `y`, let's use the `LabelEncoder` provided by `sklearn` to encode its three class values.

"""

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Encode the target variable
y = label_encoder.fit_transform(y_raw.values.ravel())
# Note that ravel() function flattens the vector.

"""The encoded target variable will only contain values `0=In Moderation`, `1=Less Often`, `2=More Often`.

"""

np.unique(y, return_counts=True)

"""## Train logistic regression models

First, let's split the dataset into a training and a testing dataset. Training dataset will be used to train and (maybe) tune models, and testing dataset will be used to evaluate the models. Note that you may also split the training dataset into train and validation sets where the validation dataset is only used to tune the model and to set the model parameters.
"""

# First, let's split the training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state = rs)

"""Let's look at the shapes of the split datasets:

"""

print(f"Training dataset shape, X_train: {X_train.shape}, y_train: {y_train.shape}")

print(f"Testing dataset shape, X_test: {X_test.shape}, y_test: {y_test.shape}")

"""OK, now we have the training and testing datasets ready, let's start the model training task.

We first define a `sklearn.linear_model.LogisticRegression` model with the following arguments, you can check the comment for each argument for what it means.
"""

# L2 penalty to shrink coefficients without removing any features from the model
penalty= 'l2'
# Our classification problem is multinomial
multi_class = 'multinomial'
# Use lbfgs for L2 penalty and multinomial classes
solver = 'lbfgs'
# Max iteration = 1000
max_iter = 1000

l2_model = LogisticRegression(random_state=rs, penalty=penalty, solver=solver, max_iter=max_iter)

"""Let's train the model with training input data `X_train` and labels `y_train`:

"""

l2_model.fit(X_train, y_train)

l2_preds = l2_model.predict(X_test)

"""Because we may need to evaluate the model multiple times with different model hyper parameters, here we define an utility method to take the ground truths `y_test` and the predictions `preds`, and return a Python `dict` with `accuracy`, `recall`, `precision`, and `f1score`.

"""

def evaluate_metrics(yt, yp):
    results_pos = {}
    results_pos['accuracy'] = accuracy_score(yt, yp)
    precision, recall, f_beta, _ = precision_recall_fscore_support(yt, yp)
    results_pos['recall'] = recall
    results_pos['precision'] = precision
    results_pos['f1score'] = f_beta
    return results_pos

evaluate_metrics(y_test, l2_preds)

"""As we can see from  the above evaluation results, the logistic regression model has relatively good performance on this multinomial classification task. The overall accuracy is around `0.77` and the f1score is around `0.8`. Note that for `recall`, `precision`, and `f1score`, we output the values for each class to see how the model performs on an individual class. And, we can see from the results, the recall for `class=2` (More often) is not very good. This is actually a common problem called imbalanced classification challenge. We will introduce solution to this problem later in this course.

Next, let's try defining another logistic regression model with l1 penality this time, to see if our classification performance would be improved.
"""

# L1 penalty to shrink coefficients without removing any features from the model
penalty= 'l1'
# Our classification problem is multinomial
multi_class = 'multinomial'
# Use saga for L1 penalty and multinomial classes
solver = 'saga'
# Max iteration = 1000
max_iter = 1000

"""Then we define another logistic regression model with above arguments using l1 penality and related solver.

"""

# Define a logistic regression model with above arguments
l1_model = LogisticRegression(random_state=rs, penalty=penalty, solver=solver, max_iter = 1000)

"""We can start to train the new `l1_model` with the new taining dataset.

"""

l1_model.fit(X_train, y_train)

"""And, make predictions using the input in the test dataset.

"""

l1_preds = l1_model.predict(X_test)

"""We can also check the class probability distribution using the `predict_proba` function. For example, we want to see the probabilities of belonging to each class for the first instance in the test dataset:

"""

odd_ratios = l1_model.predict_proba(X_test[:1, :])[0]
odd_ratios

"""We can see that  Class 1 has the largest probability 0.96. As such, the model prediction for this instance will be class `1` and this is the same as the `predict` method.

"""

l1_model.predict(X_test[:1, :])[0]

"""Given the true labels (`y_test`) and predictions, we can evaluate the model performance by calling the utility `evaluate_metrics`  method.

"""

evaluate_metrics(y_test, l1_preds)

"""Now, we can see this logistic regression with l1 penalty has much better performance than l2. One possible reason is that l1 penalty may remove some correlated feature variables by shrinking their coefficents to zero. As such, the model is much simplified to avoid overfitting on the training data and better aligned with the logistic regression assumption that all features should be independent.

### Confusion Matrix

We can also plot the confusion matrix based on the true labels and predictions using the `confusion_matrix` method provided by `sklearn`,
"""

cf = confusion_matrix(y_test, l1_preds, normalize='true')
cf

"""and easily visualize it using a heatmap method provided by `seaborn`.

"""

sns.set_context('talk')
disp = ConfusionMatrixDisplay(confusion_matrix=cf,display_labels=l1_model.classes_)
disp.plot()
plt.show()

"""### Interpret logistic regression models

One way to interpret logistic regression models is by analyzing feature coefficients. Although it may not be as effective as the regular linear regression models because the logistic regression model has a sigmoid function, we can still get a sense for the importance or impact of each feature.

We can check the coefficients for logistic regression model using its `coef_` attribute:
"""

l1_model.coef_

"""The `coef_` is a coefficients list with three elements, one element is the actual coefficent for class 0, 1, 2. To better analyze the coefficients, let's use three utility methods to sort and visualize them.

"""

# Extract and sort feature coefficients
def get_feature_coefs(regression_model, label_index, columns):
    coef_dict = {}
    for coef, feat in zip(regression_model.coef_[label_index, :], columns):
        if abs(coef) >= 0.01:
            coef_dict[feat] = coef
    # Sort coefficients
    coef_dict = {k: v for k, v in sorted(coef_dict.items(), key=lambda item: item[1])}
    return coef_dict

# Generate bar colors based on if value is negative or positive
def get_bar_colors(values):
    color_vals = []
    for val in values:
        if val <= 0:
            color_vals.append('r')
        else:
            color_vals.append('g')
    return color_vals

# Visualize coefficients
def visualize_coefs(coef_dict):
    features = list(coef_dict.keys())
    values = list(coef_dict.values())
    y_pos = np.arange(len(features))
    color_vals = get_bar_colors(values)
    plt.rcdefaults()
    fig, ax = plt.subplots()
    ax.barh(y_pos, values, align='center', color=color_vals)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(features)
    # labels read top-to-bottom
    ax.invert_yaxis()
    ax.set_xlabel('Feature Coefficients')
    ax.set_title('')
    plt.show()

"""Then, let's visualize the sorted coefficient for class 1, the `Less Often` class:

"""

# Get the coefficents for Class 1, Less Often
coef_dict = get_feature_coefs(l1_model, 1, feature_cols)

visualize_coefs(coef_dict)

"""As we can see, unhealthy nutrients such as Saturated Fat, Sugars, Cholesterol, Total Fat, etc., have high positive coefficients. Food items containing unhealthy nutrients will have higher coeficients and will be more likely to be categorized in the 'Less Often' class.

Next, let's see the coefficents for Class 2, `More Often`:
"""

# Coefficients for Class 2
coef_dict = get_feature_coefs(l1_model, 2, feature_cols)
visualize_coefs(coef_dict)

"""Conversely, if a food item has a high amount of calories, total carbohydrates, and total fat, then it is unlikely to be categorized in the 'More Often' class.

## Coding Exercise: Train and evaluate a logistic regression model with elastic-net penality

Now, it's your turn to walk through the end-to-end process of defining, building, evaluating, and interpreting a logistic regression model.

### Define a logistic regression with elastic-net penality

*   List item
*   List item
"""

# Type your code here
# HINT: sklearn only support saga solver for elastic-net penality
# and you need to set another l1_ratio to be within 0 < l1_ratio <1, in order to actually use elastic-net

# Elastic-net mixes L1 and L2 penalties together
penalty = 'elasticnet'
multi_class = 'multinomial'
solver = 'saga'       # REQUIRED for elastic-net
max_iter = 1000
l1_ratio = 0.5        # 0.5 = equal mix of L1 and L2

en_model = LogisticRegression(
    random_state=rs,
    penalty=penalty,
    multi_class=multi_class,
    solver=solver,
    max_iter=max_iter,
    l1_ratio=l1_ratio   # must be between 0 and 1 (exclusive)
)

"""### Train the model with training data

"""

# Type your code here
en_model.fit(X_train, y_train)

en_preds = en_model.predict(X_test)

"""### Evaluate the model using accuracy, precision, recall, and F1score

"""

# Type your code here
# Use the evaluate_metrics() function already defined in the notebook
results = evaluate_metrics(y_test, en_preds)
print(results)

# OR get a full report in one line:
print(classification_report(y_test, en_preds,
      target_names=label_encoder.classes_))

"""### Plot confusion matrix

"""

# Type your code here
# Compute confusion matrix (normalized so rows sum to 1.0)
cf = confusion_matrix(y_test, en_preds, normalize='true')

# Plot it
disp = ConfusionMatrixDisplay(
    confusion_matrix=cf,
    display_labels=en_model.classes_
)
disp.plot()
plt.title("Elastic-Net Confusion Matrix")
plt.show()

"""### Interpret the model by analysing its coefficients

"""

# Type your code here
# Class 0 = "In Moderation"
coef_dict = get_feature_coefs(en_model, 0, feature_cols)
visualize_coefs(coef_dict)

# Class 1 = "Less Often"
coef_dict = get_feature_coefs(en_model, 1, feature_cols)
visualize_coefs(coef_dict)

# Class 2 = "More Often"
coef_dict = get_feature_coefs(en_model, 2, feature_cols)
visualize_coefs(coef_dict)

"""<details><summary>Click here for a sample solution</summary>

```python
# elasticnet penalty to shrink coefficients without removing any features from the model
penalty= 'elasticnet'
# Our classification problem is multinomial
multi_class = 'multinomial'
# Use saga for L1 penalty and multinomial classes
solver = 'saga'
# Max iteration = 1000
max_iter = 1000
# l1_ratio
l1_ratio = 0.1

# Define a elastic-net model
en_model = LogisticRegression(random_state=rs, penalty=penalty, multi_class=multi_class, solver=solver, max_iter = 1000, l1_ratio=l1_ratio)
en_model.fit(X_train, y_train)
# Make predictions
preds = en_model.predict(X_test)
```

</details>

## Next steps

Great! Now you have learned about and practiced applying a logistic regression model to solve a real-world food classification problem for diabetic patients. You also learned how to evaluate and interpret the trained logistic regression models.

Next, you will be learning other popular classification models with different structures, assumptions, cost functions, and application scenarios.

## Authors

[Yan Luo](https://www.linkedin.com/in/yan-luo-96288783/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML241ENSkillsNetwork31576874-2021-01-01)

### Other Contributors

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By | Change Description          |
| ----------------- | ------- | ---------- | --------------------------- |
| 2021-10-25        | 1.0     | Yan        | Created the initial version |
--!>

Copyright © 2021 IBM Corporation. All rights reserved.
"""